source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'MyProject' do
pod 'AFNetworking', '~> 4.0.0'
pod 'SDWebImage', '~> 5.11.1'
pod 'Aspects', '~> 1.4.1'
pod 'RiffleTest2', :git => "https://github.com/Riffle-1024/RiffleTest2.git"
pod 'MJRefresh','~> 3.7.2'
end
